version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: plaintext://:9092
      KAFKA_ADVERTISED_LISTENERS: plaintext://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "OriginalDicomSenderNotify:10:1,DicomReportNotify:1:1,PUMConsumerError:1:1"
      KAFKA_MESSAGE_MAX_BYTES: 1048576
    depends_on:
      - zookeeper